// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuqcnowdaulhpxftegwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cWNub3dkYXVsaHB4ZnRlZ3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDgxODgsImV4cCI6MjA1NzMyNDE4OH0.Z3i_AqqwB7kY5lEmpuvM_r6JoNIVEz5x0YJu-Uy3Iyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);